name: brakeman
version: 7.0.0
base: core24
summary: Ruby on Rails security vulnerability static analysis tool
adopt-info: brakeman
description: |
  Brakeman is a command-line tool that analyzes the source code of Ruby on
  Rails applications to find potential security vulnerabilities.

confinement: strict

layout:
  /usr/lib/ruby:
    symlink: $SNAP/usr/lib/ruby
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/ruby:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/ruby
  /usr/share/rubygems-integration/all:
    symlink: $SNAP/usr/share/rubygems-integration/all
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/rubygems-integration:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/rubygems-integration

apps:
  brakeman:
    command: bin/brakeman
    plugs:
      - home
      - removable-media

parts:
  brakeman:
    source: https://github.com/presidentbeef/brakeman.git
    plugin: dump
    build-packages:
      - ruby
    stage-packages:
      # mostly from https://github.com/presidentbeef/brakeman/blob/main/gem_common.rb
      - racc
      - ruby
      - ruby-csv
      - ruby-erubis
      - ruby-haml
      - ruby-highline
      - ruby-parallel
      - ruby-ruby-parser
      - ruby-ruby2ruby
      - ruby-sexp-processor
      - ruby-slim
      - ruby-terminal-table
    override-build: |
      craftctl default
      # don't try and flock() gemspecs since this is blocked by AppArmor - see
      # https://github.com/rubygems/rubygems/pull/5278 in particular
      # https://github.com/rubygems/rubygems/pull/5278/commits/27b682c81226838b1254ac5843a3f5b1cb20f076
      sed -i 's|!solaris_platform|win_platform|' $SNAPCRAFT_PART_INSTALL/usr/lib/ruby/vendor_ruby/rubygems.rb


