name: brakeman
version: 8.0.1
base: core24
summary: Ruby on Rails security vulnerability static analysis tool
adopt-info: brakeman
description: |
  Brakeman is a command-line tool that analyzes the source code of Ruby on
  Rails applications to find potential security vulnerabilities.

confinement: strict

layout:
  /usr/lib/ruby:
    symlink: $SNAP/usr/lib/ruby
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/ruby:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/ruby
  /usr/share/rubygems-integration/all:
    symlink: $SNAP/usr/share/rubygems-integration/all
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/rubygems-integration:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/rubygems-integration

apps:
  brakeman:
    command: bin/brakeman
    plugs:
      - home
      - removable-media

parts:
  brakeman:
    source: https://github.com/presidentbeef/brakeman.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    plugin: dump
    build-packages:
      - ruby
    stage-packages:
      # mostly from https://github.com/presidentbeef/brakeman/blob/main/gem_common.rb
      - racc
      - ruby
      - ruby-csv
      - ruby-erubi
      - ruby-haml
      - ruby-highline
      - ruby-parallel
      - ruby-ruby-parser
      - ruby-ruby2ruby
      - ruby-sexp-processor
      - ruby-slim
      - ruby-terminal-table
      - ruby-unicode-display-width
    override-build: |
      craftctl default
      # don't try and flock() gemspecs since this is blocked by AppArmor - see
      # https://github.com/rubygems/rubygems/pull/5278 in particular
      # https://github.com/rubygems/rubygems/pull/5278/commits/27b682c81226838b1254ac5843a3f5b1cb20f076
      sed -i 's|!solaris_platform|win_platform|' $SNAPCRAFT_PART_INSTALL/usr/lib/ruby/vendor_ruby/rubygems.rb
      # also fixup DEBIAN_DATA_DIRECTORY in ruby-unicode-display-width
      sed -i "s|DEBIAN_DATA_DIRECTORY = '/usr|DEBIAN_DATA_DIRECTORY = ENV[\"SNAP\"] + '/usr|" $SNAPCRAFT_PART_INSTALL/usr/lib/ruby/vendor_ruby/unicode/display_width/constants.rb

  reline:
    plugin: dump
    source: https://github.com/ruby/reline.git
    source-tag: v0.6.3
    build-packages:
      - libffi-dev
      - ruby
      - ruby-bundler
      - ruby-dev
    override-build: |
      bundle install
      craftctl default
    # don't stage some bits that conflict with the brakeman part
    stage:
      - -Gemfile
      - -Gemfile.lock
      - -README.md
      - -Rakefile

  prism:
    plugin: dump
    source: https://github.com/ruby/prism.git
    source-tag: v1.9.0
    build-packages:
      - libyaml-dev
      - ruby
      - ruby-bundler
      - ruby-dev
      - make
      - gcc
    override-build: |
      bundle install
      bundle exec rake compile
      craftctl default
    # don't stage some bits that conflict with the brakeman part
    stage:
      - -CODE_OF_CONDUCT.md
      - -CONTRIBUTING.md
      - -Gemfile
      - -Gemfile.lock
      - -LICENSE.md
      - -README.md
      - -Rakefile
