name: brakeman
base: core18
summary: Ruby on Rails security vulnerability static analysis tool
adopt-info: brakeman
description: |
  Brakeman is a command-line tool that analyzes the source code of Ruby on
  Rails applications to find potential security vulnerabilities.

confinement: strict

apps:
  brakeman:
    command: bin/brakeman
    plugs:
      - home
      - removable-media

parts:
  brakeman:
    plugin: ruby
    source: .
    ruby-version: 3.0.6
    gems:
      - brakeman
    override-build: |
      snapcraftctl build
      snapcraftctl set-version $(RUBYLIB=$SNAPCRAFT_PART_INSTALL/lib/ruby/3.0.0:$(find $SNAPCRAFT_PART_INSTALL -name rbconfig.rb -exec dirname {} \;) GEM_HOME=$SNAPCRAFT_PART_INSTALL/lib/ruby/gems/3.0.0 $SNAPCRAFT_PART_INSTALL/bin/ruby $SNAPCRAFT_PART_INSTALL/bin/brakeman --version | awk '{print $2}')
      snapcraftctl set-grade stable

